### ISSUE TITLE
Modifica namespace schema.org

### ISSUE THREAD

**Issue by smartrics** [Comune-Milano/ontologie-iot-urbani#1]
*Descrizione*
Le ontologie hanno riferimenti esterni a `http://schema.org` (vedi [qui](https://github.com/Comune-Milano/ontologie-iot-urbani/search?l=Turtle&q=schema.org)). 
La proposta per questa modifica e' di cambiare i riferimenti da `http://schema.org` a `https://schema.org`
Sebbene `schema.org` permetta entrambi (come da [FAQ #19](https://schema.org/docs/faq.html#19)) e' pratica comune utilizzare `https`. 

*Attori*
tutti

_Motivazione_: 
Utilizzare `https` aumenta in grado di interoperabilita' di questa ontologia con altre , sulla base del fatto che `https` e' di uso comune.
Qui ad IOTICS lavoriamo per abilitare diverse organizzazioni a scambiare e condividere data in maniera sicura e efficiente. Alcune dele nostre applicazioni utilizzano gia `https://schema.org`. Vorremmo utilizzare `urbaniot` ma e' complicato costruire queries federate che eseguano joins remote che tengano in considerazione `https://schema.org` e `http://schema.org` allo stesso tempo.

**Comment by marioscrock** [comment]
Grazie @smartrics per la issue. Abbiamo aggiornato il namespace come proposto per favorire il riutilizzo delle ontologie.
